### ISSUE TITLE
Possible to use email and username?

### ISSUE THREAD

**Issue by operatorone** [1up-lab/contao-email-login#1]
Hi,

is it possible to use the email address or a username at the same time? For example, I got two member groups. One membergroup should use a username, the other should use the email address and both should be redirected to different landign pages.

Cheers,
operatorone

**Comment by bytehead** [comment]
Yes, it works both ways: https://docs.contao.org/books/api/extensions/hooks/importUser.html

> The importUser hook is triggered when a username cannot be found in the database. It passes the username, the password and the table name as arguments and expects a boolean return value.

If there is no user with a matching username the system will give a try with the email address.
